### PR TITLE
created registration and login function

### PR DESCRIPTION
**Pull request by jadentel**
Hey,

I'm excited to present this pull request that introduces essential user management features to our application. Here's a breakdown of the changes I've made:

- User Registration:

Created a new registration module that enables users to sign up securely.
Implemented input validation to ensure accurate user data during registration.

- User Login:
Added a robust login system that authenticates users securely.
Utilized session management to maintain user states.

- User Logout:
Integrated a logout mechanism for users to log out safely.
Managed session termination to enhance data security.

- Navbar Integration (if necessary):

Provided an option to integrate these new features into the application's navbar.
Users can conveniently access registration, login, and logout actions.

Your feedback is welcome.

Thank you for taking the time to review this pull request.

Best regards,
Jaden

### CODE REVIEW

**Comment by jadentel** [comment]
Hi,
Please accept my pull request if it meets the specification, thanks.

**Comment by miikkuu** [comment]
"Hey @jadentel, sorry, it was a busy week for me. I just pulled this and found it to be good for the most part. However, I would like to request a few changes. If you are up for it, please let me know; it would be greatly appreciated.

I would like the project to start with the login page.
Please consider adding the navbar.
If possible, add a feature where the logged-in user can see their previous shortened links on the main page itself (sidebar).
A simple update in README.md related to Pipfile and the new features would be appreciated.
If you have limited time, you can skip the third and fourth points, but I would really appreciate it if you could address the first two points; they would greatly improve the project."

**Comment by miikkuu** [comment]
"Hey @jadentel, sorry, it was a busy week for me. I just pulled this and found it to be good for the most part. However, I would like to request a few changes. If you are up for it, please let me know; it would be greatly appreciated.

1.I would like the project to start with the login page.
2.Please consider adding the navbar.
3.If possible, add a feature where the logged-in user can see their previous shortened links on the main page itself (sidebar).
4.A simple update in README.md related to Pipfile and the new features would be appreciated.

If you have limited time, you can skip the third and fourth points, but I would really appreciate it if you could address the first two points; they would greatly improve the project."

**Comment by miikkuu** [comment]
Or the second way is just wait for a couple of days. I will do it myself by the weekend.

**Pull request merged**
